In [2]:
import io
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
conn = sqlite3.connect('conn_despesas_publicas_tp1.db')
cursor = conn.cursor()

In [23]:
f = io.open('despesas_publicas_tp1.sql', 'rb')
sql = f.read()
cursor.executescript(sql.decode('iso8859_1'))

In [39]:
#1
df = pd.read_sql_query("SELECT S.COD_SUBFUNCAO, S.NOME_SUBFUNCAO FROM FUNCAO F NATURAL JOIN DETALHAMENTO_FUNCAO DF NATURAL JOIN SUBFUNCAO S WHERE F.COD_FUNCAO = (SELECT COD_FUNCAO FROM FUNCAO F NATURAL JOIN DETALHAMENTO_FUNCAO DF NATURAL JOIN SUBFUNCAO S GROUP BY DF.COD_FUNCAO ORDER BY COUNT(*) DESC LIMIT 1);", conn)
print(len(df.columns))
print(len(df))

2
7

In [62]:
#2
df = pd.read_sql_query("SELECT F.NOME_FUNCAO, S.NOME_SUBFUNCAO, SUM(DP.VALOR_DESPESA) VT FROM DESPESA_PUBLICA DP NATURAL JOIN FUNCAO F NATURAL JOIN DETALHAMENTO_FUNCAO DF NATURAL JOIN SUBFUNCAO S GROUP BY F.COD_FUNCAO, S.COD_SUBFUNCAO HAVING VT >= 200000;",conn)
print(len(df.columns))
print(len(df))

3
2

In [63]:
#3
df = pd.read_sql_query("SELECT O.NOME_ORGAO, SUM(DP.VALOR_DESPESA) VT FROM DESPESA_PUBLICA DP NATURAL JOIN ORGAO O WHERE DP.ANO_DESPESA = 2018 GROUP BY DP.COD_ORGAO ORDER BY VT DESC;",conn)
print(len(df.columns))
print(len(df))

2
14

In [64]:
#6
df = pd.read_sql_query("SELECT F.NOME_FUNCAO, S.NOME_SUBFUNCAO, SUM(DP.VALOR_DESPESA) VT FROM DESPESA_PUBLICA DP NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN FUNCAO F NATURAL JOIN SUBFUNCAO S WHERE DP.COD_PROGRAMA_GOVERNO = (SELECT COD_PROGRAMA_GOVERNO FROM PROGRAMA_GOVERNO WHERE NOME_PROGRAMA_GOVERNO = \"MAIS MEDICOS\") AND DP.MES_DESPESA >= 7 AND DP.MES_DESPESA <= 9 AND DP.ANO_DESPESA = 2018;",conn)
print(len(df.columns))
print(len(df))
df

3
1

  NOME_FUNCAO  NOME_SUBFUNCAO     VT
0       Saúde  Atenção básica  13400

In [65]:
#7
df = pd.read_sql_query("SELECT O.NOME_ORGAO, COUNT(DISTINCT PG.NOME_PROGRAMA_GOVERNO) NPROGS FROM ORGAO O NATURAL JOIN DESPESA_PUBLICA DP NATURAL JOIN PROGRAMA_GOVERNO PG WHERE DP.VALOR_DESPESA > 0 GROUP BY O.COD_ORGAO;", conn)
print(len(df.columns))
print(len(df))
df

2
5

                                      NOME_ORGAO  NPROGS
0  Ministério da Agricultura, Pecuária e Abastec       2
1                         Ministério da Educação       4
2                            Ministério da Saúde       2
3                           Ministério da Defesa       2
4           Ministério do Desenvolvimento Social       1

In [66]:
#10
df = pd.read_sql_query("SELECT DP.COD_DESPESA, DP.MES_DESPESA, DP.ANO_DESPESA, DP.MODALIDADE_DESPESA, DP.VALOR_DESPESA FROM DESPESA_PUBLICA DP WHERE DP.COD_ORGAO = (SELECT O.COD_ORGAO FROM DESPESA_PUBLICA DP NATURAL JOIN ORGAO O WHERE DP.ANO_DESPESA = 2018 GROUP BY DP.COD_ORGAO ORDER BY SUM(DP.VALOR_DESPESA) DESC LIMIT 1);",conn)
print(len(df.columns))
print(len(df))
df

5
56

,COD_DESPESA,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,VALOR_DESPESA
0,827,1,2018,Reserva de Contingência,0.0
1,828,2,2018,Reserva de Contingência,0.0
2,829,3,2018,Reserva de Contingência,0.0
3,830,4,2018,Reserva de Contingência,0.0
4,831,5,2018,Reserva de Contingência,0.0
5,832,6,2018,Reserva de Contingência,0.0
6,833,7,2018,Reserva de Contingência,0.0
7,834,8,2018,Reserva de Contingência,0.0
8,835,9,2018,Reserva de Contingência,334126.7
9,836,10,2018,Reserva de Contingência,0.0
10,837,11,2018,Reserva de Contingência,0.0
11,838,12,2018,Reserva de Contingência,0.0
12,839,12,2018,Transferências a Instituições Privadas sem Fin...,0.0
13,840,1,2018,Reserva de Contingência,0.0
14,841,2,2018,Reserva de Contingência,0.0
15,842,3,2018,Reserva de Contingência,0.0
16,843,4,2018,Reserva de Contingência,0.0
17,844,5,2018,Reserva de Contingência,0.0
18,845,6,2018,Reserva de Contingência,0.0
19,846,8,2018,Reserva de Contingência,0.0
20,847,12,2018,Reserva de Contingência,0.0
21,848,1,2018,Reserva de Contingência,0.0
22,849,1,2018,Reserva de Contingência,0.0
23,850,2,2018,Reserva de Contingência,0.0
24,851,3,2018,Reserva de Contingência,0.0
25,852,4,2018,Reserva de Contingência,0.0
26,853,5,2018,Reserva de Contingência,0.0
27,854,6,2018,Reserva de Contingência,0.0
28,855,7,2018,Reserva de Contingência,0.0
29,856,8,2018,Reserva de Contingência,0.0
30,857,9,2018,Reserva de Contingência,0.0
31,858,10,2018,Reserva de Contingência,19250.0
32,859,11,2018,Reserva de Contingência,0.0
33,860,12,2018,Reserva de Contingência,0.0
34,861,1,2018,Reserva de Contingência,0.0
35,862,2,2018,Reserva de Contingência,0.0
36,863,3,2018,Reserva de Contingência,0.0
37,864,4,2018,Reserva de Contingência,0.0
38,865,5,2018,Reserva de Contingência,0.0
39,866,6,2018,Reserva de Contingência,0.0
40,867,7,2018,Reserva de Contingência,0.0
41,868,8,2018,Reserva de Contingência,0.0
42,869,9,2018,Reserva de Contingência,0.0
43,870,10,2018,Reserva de Contingência,0.0
44,871,11,2018,Reserva de Contingência,0.0
45,872,12,2018,Reserva de Contingência,0.0
46,873,3,2018,Reserva de Contingência,0.0
47,874,4,2018,Reserva de Contingência,0.0
48,875,5,2018,Reserva de Contingência,0.0
49,876,6,2018,Reserva de Contingência,0.0
50,877,7,2018,Reserva de Contingência,0.0
51,878,8,2018,Reserva de Contingência,0.0
52,879,9,2018,Reserva de Contingência,0.0
53,880,10,2018,Reserva de Contingência,0.0
54,881,11,2018,Reserva de Contingência,0.0
55,882,12,2018,Reserva de Contingência,0.0

In [67]:
#12
df = pd.read_sql_query("SELECT FUNCAO.NOME_FUNCAO, SUBFUNCAO.NOME_SUBFUNCAO FROM FUNCAO NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN SUBFUNCAO;",conn)
print(len(df.columns))
print(len(df))
df.head()

2
40

           NOME_FUNCAO       NOME_SUBFUNCAO
0  Essencial à justiça   Comunicação social
1      Defesa nacional  Administração geral
2      Defesa nacional     Defesa terrestre
3    Segurança pública  Administração geral
4    Segurança pública         Policiamento

In [68]:
#13
df = pd.read_sql_query("SELECT DP.MODALIDADE_DESPESA, DP.VALOR_DESPESA, PG.NOME_PROGRAMA_GOVERNO FROM PROGRAMA_GOVERNO PG NATURAL JOIN DESPESA_PUBLICA DP WHERE DP.MODALIDADE_DESPESA = 'Reserva de Contingência'",conn)
print(len(df.columns))
print(len(df))
df

3
676

          MODALIDADE_DESPESA  VALOR_DESPESA     NOME_PROGRAMA_GOVERNO
0    Reserva de Contingência            0.0        BRASIL SEM MISERIA
1    Reserva de Contingência            0.0        BRASIL SEM MISERIA
2    Reserva de Contingência            0.0        BRASIL SEM MISERIA
3    Reserva de Contingência            0.0        BRASIL SEM MISERIA
4    Reserva de Contingência            0.0        BRASIL SEM MISERIA
5    Reserva de Contingência            0.0        BRASIL SEM MISERIA
6    Reserva de Contingência            0.0        BRASIL SEM MISERIA
7    Reserva de Contingência            0.0        BRASIL SEM MISERIA
8    Reserva de Contingência            0.0     VIOLENCIA NO TRANSITO
9    Reserva de Contingência            0.0     VIOLENCIA NO TRANSITO
10   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
11   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
12   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
13   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
14   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
15   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
16   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
17   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
18   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
19   Reserva de Contingência            0.0  TERRITORIOS DA CIDADANIA
20   Reserva de Contingência            0.0        BRASIL SEM MISERIA
21   Reserva de Contingência         8215.7        BRASIL SEM MISERIA
22   Reserva de Contingência            0.0        BRASIL SEM MISERIA
23   Reserva de Contingência            0.0        BRASIL SEM MISERIA
24   Reserva de Contingência            0.0        BRASIL SEM MISERIA
25   Reserva de Contingência            0.0        BRASIL SEM MISERIA
26   Reserva de Contingência            0.0        BRASIL SEM MISERIA
27   Reserva de Contingência            0.0        BRASIL SEM MISERIA
28   Reserva de Contingência            0.0        BRASIL SEM MISERIA
29   Reserva de Contingência            0.0        BRASIL SEM MISERIA
..                       ...            ...                       ...
646  Reserva de Contingência            0.0        BRASIL SEM MISERIA
647  Reserva de Contingência            0.0        BRASIL SEM MISERIA
648  Reserva de Contingência            0.0        BRASIL SEM MISERIA
649  Reserva de Contingência            0.0        BRASIL SEM MISERIA
650  Reserva de Contingência            0.0        BRASIL SEM MISERIA
651  Reserva de Contingência            0.0        BRASIL SEM MISERIA
652  Reserva de Contingência            0.0        BRASIL SEM MISERIA
653  Reserva de Contingência            0.0        BRASIL SEM MISERIA
654  Reserva de Contingência            0.0        BRASIL SEM MISERIA
655  Reserva de Contingência            0.0        BRASIL SEM MISERIA
656  Reserva de Contingência            0.0        BRASIL SEM MISERIA
657  Reserva de Contingência            0.0        BRASIL SEM MISERIA
658  Reserva de Contingência            0.0        BRASIL SEM MISERIA
659  Reserva de Contingência            0.0        BRASIL SEM MISERIA
660  Reserva de Contingência            0.0        BRASIL SEM MISERIA
661  Reserva de Contingência            0.0        BRASIL SEM MISERIA
662  Reserva de Contingência            0.0        BRASIL SEM MISERIA
663  Reserva de Contingência            0.0        BRASIL SEM MISERIA
664  Reserva de Contingência            0.0        BRASIL SEM MISERIA
665  Reserva de Contingência            0.0        BRASIL SEM MISERIA
666  Reserva de Contingência            0.0        BRASIL SEM MISERIA
667  Reserva de Contingência            0.0        BRASIL SEM MISERIA
668  Reserva de Contingência            0.0        BRASIL SEM MISERIA
669  Reserva de Contingência            0.0        BRASIL SEM MISERIA
670  Reserva de Contingência            0.0        BRASIL SEM MISERIA
671  Reserva de Contingência            0.0        BRASIL SEM MISERIA
672  Reserva de Contingência            0.0        BRASIL SEM MISERIA
673  Reserva de Contingência            0.0        BRASIL SEM MISERIA
674  Reserva de Contingência            0.0        BRASIL SEM MISERIA
675  Reserva de Contingência            0.0        BRASIL SEM MISERIA

[676 rows x 3 columns]

In [69]:
#14
df = pd.read_sql_query("SELECT DP.VALOR_DESPESA, O.NOME_ORGAO FROM DESPESA_PUBLICA DP NATURAL JOIN ORGAO O WHERE O.NOME_ORGAO = 'Ministério da Fazenda';",conn)
print(len(df.columns))
print(len(df))
df

2
13

    VALOR_DESPESA             NOME_ORGAO
0               0  Ministério da Fazenda
1               0  Ministério da Fazenda
2               0  Ministério da Fazenda
3               0  Ministério da Fazenda
4               0  Ministério da Fazenda
5               0  Ministério da Fazenda
6               0  Ministério da Fazenda
7               0  Ministério da Fazenda
8               0  Ministério da Fazenda
9               0  Ministério da Fazenda
10              0  Ministério da Fazenda
11              0  Ministério da Fazenda
12              0  Ministério da Fazenda

In [70]:
#15
df = pd.read_sql_query("SELECT PG.NOME_PROGRAMA_GOVERNO, DP.VALOR_DESPESA FROM DESPESA_PUBLICA DP NATURAL JOIN ORGAO O NATURAL JOIN PROGRAMA_GOVERNO PG WHERE O.NOME_ORGAO = 'Ministério da Saúde'",conn)
print(len(df.columns))
print(len(df))
df

2
219

    NOME_PROGRAMA_GOVERNO  VALOR_DESPESA
0        VIVER SEM LIMITE            0.0
1        VIVER SEM LIMITE            0.0
2        VIVER SEM LIMITE            0.0
3        VIVER SEM LIMITE            0.0
4        VIVER SEM LIMITE            0.0
5        VIVER SEM LIMITE            0.0
6        VIVER SEM LIMITE            0.0
7        VIVER SEM LIMITE            0.0
8        VIVER SEM LIMITE            0.0
9        VIVER SEM LIMITE            0.0
10       VIVER SEM LIMITE            0.0
11       VIVER SEM LIMITE            0.0
12       VIVER SEM LIMITE            0.0
13       VIVER SEM LIMITE            0.0
14       VIVER SEM LIMITE            0.0
15       VIVER SEM LIMITE            0.0
16       VIVER SEM LIMITE            0.0
17       VIVER SEM LIMITE            0.0
18       VIVER SEM LIMITE            0.0
19       VIVER SEM LIMITE            0.0
20       VIVER SEM LIMITE            0.0
21       VIVER SEM LIMITE            0.0
22       VIVER SEM LIMITE            0.0
23       VIVER SEM LIMITE            0.0
24       VIVER SEM LIMITE            0.0
25       VIVER SEM LIMITE            0.0
26       VIVER SEM LIMITE            0.0
27       VIVER SEM LIMITE            0.0
28       VIVER SEM LIMITE            0.0
29       VIVER SEM LIMITE            0.0
..                    ...            ...
189          MAIS MEDICOS            0.0
190          MAIS MEDICOS            0.0
191          MAIS MEDICOS            0.0
192          MAIS MEDICOS            0.0
193          MAIS MEDICOS            0.0
194          MAIS MEDICOS            0.0
195          MAIS MEDICOS            0.0
196          MAIS MEDICOS            0.0
197          MAIS MEDICOS            0.0
198          MAIS MEDICOS            0.0
199          MAIS MEDICOS            0.0
200          MAIS MEDICOS            0.0
201          MAIS MEDICOS            0.0
202          MAIS MEDICOS            0.0
203          MAIS MEDICOS        11000.0
204          MAIS MEDICOS            0.0
205          MAIS MEDICOS            0.0
206          MAIS MEDICOS         1000.0
207          MAIS MEDICOS            0.0
208          MAIS MEDICOS            0.0
209          MAIS MEDICOS            0.0
210          MAIS MEDICOS            0.0
211          MAIS MEDICOS            0.0
212          MAIS MEDICOS            0.0
213          MAIS MEDICOS            0.0
214          MAIS MEDICOS            0.0
215          MAIS MEDICOS            0.0
216          MAIS MEDICOS            0.0
217          MAIS MEDICOS            0.0
218          MAIS MEDICOS            0.0

[219 rows x 2 columns]

In [ ]:
conn.close()